Fix nonce handling logic in create_attribute
substrate-developer-hub/pallet-did pull request #13
Opened 2020-12-10 00:02 UTC by danforbes

2020-12-11 05:17 UTC, jimmychu0807 approved these changes
lgtm. Maybe @riusricardo would want to have a peek in this PR as well?

2020-12-15 02:38 UTC, riusricardo commented on src/lib.rs
> +            0u64 => return None,
What is the advantage of hashing a `None` instead of a `0`?

2020-12-15 02:40 UTC, riusricardo commented on src/lib.rs
> +            0u64 => return None,
I'm mostly thinking that in case of a `none` it could be ignoring the `nonce` attribute in the hash when you lookup the id.

2020-12-16 14:49 UTC, riusricardo commented on src/lib.rs
> +            0u64 => return None,
I didn't see that you were returning early here. It isn't hashing a None but this change will return that attribute with nonce `0` is invalid and that isn't right.

2020-12-16 14:54 UTC, riusricardo commented on src/tests.rs
> +fn add_remove_add_remove_attr() {
It will become a better test if you use the `fn attribute_and_id` to test the change that you made there.

2020-12-16 16:07 UTC, riusricardo requested changes

2020-12-16 16:07 UTC, riusricardo commented on src/lib.rs
> +        let id = (&identity, name, nonce).using_encoded(blake2_256);
This doesn't look good. It should be `lookup_nonce`. Using `nonce` will allow to have 2 attributes with the same name.

2020-12-16 16:44 UTC, riusricardo commented on src/lib.rs
>          if <AttributeOf<T>>::contains_key((&identity, &id)) {
```suggestion
        if nonce > 0 && <AttributeOf<T>>::contains_key((&identity, &id)) {
```

2020-12-16 16:44 UTC, riusricardo commented on src/lib.rs
>          if <AttributeOf<T>>::contains_key((&identity, &id)) {
This check will help to address the issue you want to fix.

2020-12-16 18:30 UTC, riusricardo commented on src/lib.rs
> +        let id = (&identity, name, nonce).using_encoded(blake2_256);
```suggestion
        let mut id = (&identity, name, lookup_nonce).using_encoded(blake2_256);
```

2020-12-16 18:32 UTC, riusricardo commented on src/lib.rs
>              nonce = nonce.checked_add(1).ok_or(Error::<T>::Overflow)?;
```suggestion
            id = (&identity, name, nonce).using_encoded(blake2_256);
            // Prevent panic overflow
            nonce = nonce.checked_add(1).ok_or(Error::<T>::Overflow)?;
```

2020-12-16 18:56 UTC, riusricardo approved these changes

2020-12-16 23:29 UTC, merged